name: flutter_aad_example
description: Am example of using flutter_aad.
version: 0.0.9
author: Matthew Clark <mclark4386@gmail.com>
homepage: https://github.com/mclark4386/flutter_aad

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_aad: ^0.0.9

dev_dependencies:
  test: ^1.3.0
  test_coverage: ^0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
