name: flutter_aad
description: A Dart package for interacting with the Azure Active Directiory platform (v1 and v2) and Sharepoint.
version: 0.4.0
homepage: https://github.com/crimercbddev/flutter_aad

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  http: 
  meta: 
  corsac_jwt:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
