name: flutter_aad
description: A Dart package for interacting with the Azure Active Directiory platform (v1 and v2).
version: 0.2.0
author: Matthew Clark <mclark4386@gmail.com>
homepage: https://github.com/mclark4386/flutter_aad

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ^0.11.0
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.0
  test_coverage: ^0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
